In [63]:
from langchain_community.document_loaders import TextLoader
from langchain_text_splitters import CharacterTextSplitter
from langchain_huggingface import HuggingFaceEmbeddings
from langchain_chroma import Chroma

In [64]:
from dotenv import load_dotenv

load_dotenv()

True

In [65]:
import pandas as pd

books = pd.read_csv("books_cleaned.csv")

In [66]:
books

,isbn13,isbn10,title,authors,categories,thumbnail,description,published_year,average_rating,num_pages,ratings_count,title_and_subtitle,tagged_description
0,9780002005883,0002005883,Gilead,Marilynne Robinson,Fiction,http://books.google.com/books/content?id=KQZCP...,A NOVEL THAT READERS and critics have been eag...,2004.0,3.85,247.0,361.0,Gilead,9780002005883 A NOVEL THAT READERS and critics...
1,9780002261982,0002261987,Spider's Web,Charles Osborne;Agatha Christie,Detective and mystery stories,http://books.google.com/books/content?id=gA5GP...,A new 'Christie for Christmas' -- a full-lengt...,2000.0,3.83,241.0,5164.0,Spider's Web: A Novel,9780002261982 A new 'Christie for Christmas' -...
2,9780006178736,0006178731,Rage of angels,Sidney Sheldon,Fiction,http://books.google.com/books/content?id=FKo2T...,"A memorable, mesmerizing heroine Jennifer -- b...",1993.0,3.93,512.0,29532.0,Rage of angels,"9780006178736 A memorable, mesmerizing heroine..."
3,9780006280897,0006280897,The Four Loves,Clive Staples Lewis,Christian life,http://books.google.com/books/content?id=XhQ5X...,Lewis' work on the nature of love divides love...,2002.0,4.15,170.0,33684.0,The Four Loves,9780006280897 Lewis' work on the nature of lov...
4,9780006280934,0006280935,The Problem of Pain,Clive Staples Lewis,Christian life,http://books.google.com/books/content?id=Kk-uV...,"""In The Problem of Pain, C.S. Lewis, one of th...",2002.0,4.09,176.0,37569.0,The Problem of Pain,"9780006280934 ""In The Problem of Pain, C.S. Le..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...
5192,9788172235222,8172235224,Mistaken Identity,Nayantara Sahgal,Indic fiction (English),http://books.google.com/books/content?id=q-tKP...,On A Train Journey Home To North India After L...,2003.0,2.93,324.0,0.0,Mistaken Identity,9788172235222 On A Train Journey Home To North...
5193,9788173031014,8173031010,Journey to the East,Hermann Hesse,Adventure stories,http://books.google.com/books/content?id=rq6JP...,This book tells the tale of a man who goes on ...,2002.0,3.70,175.0,24.0,Journey to the East,9788173031014 This book tells the tale of a ma...
5194,9788179921623,817992162X,The Monk Who Sold His Ferrari: A Fable About F...,Robin Sharma,Health & Fitness,http://books.google.com/books/content?id=c_7mf...,"Wisdom to Create a Life of Passion, Purpose, a...",2003.0,3.82,198.0,1568.0,The Monk Who Sold His Ferrari: A Fable About F...,9788179921623 Wisdom to Create a Life of Passi...
5195,9788185300535,8185300534,I Am that,Sri Nisargadatta Maharaj;Sudhakar S. Dikshit,Philosophy,http://books.google.com/books/content?id=Fv_JP...,This collection of the timeless teachings of o...,1999.0,4.51,531.0,104.0,I Am that: Talks with Sri Nisargadatta Maharaj,9788185300535 This collection of the timeless ...
5196,9789027712059,9027712050,The Berlin Phenomenology,Georg Wilhelm Friedrich Hegel,History,http://books.google.com/books/content?id=Vy7Sk...,Since the three volume edition ofHegel's Philo...,1981.0,0.00,210.0,0.0,The Berlin Phenomenology,9789027712059 Since the three volume edition o...

In [67]:
books['tagged_description']

0       9780002005883 A NOVEL THAT READERS and critics...
1       9780002261982 A new 'Christie for Christmas' -...
2       9780006178736 A memorable, mesmerizing heroine...
3       9780006280897 Lewis' work on the nature of lov...
4       9780006280934 "In The Problem of Pain, C.S. Le...
                              ...
5192    9788172235222 On A Train Journey Home To North...
5193    9788173031014 This book tells the tale of a ma...
5194    9788179921623 Wisdom to Create a Life of Passi...
5195    9788185300535 This collection of the timeless ...
5196    9789027712059 Since the three volume edition o...
Name: tagged_description, Length: 5197, dtype: str

In [68]:
books["tagged_description"].to_csv("tagged_description.txt",
                                   index = False,
                                   header = False)

In [69]:
raw_documents = TextLoader("tagged_description.txt").load() # Load teext from raw doc
text_splitter = CharacterTextSplitter(chunk_size=10000, chunk_overlap=0, separator="\n")
documents = text_splitter.split_documents(raw_documents)

In [70]:
documents[0]

Document(metadata={'source': 'tagged_description.txt'}, page_content='"9780002005883 A NOVEL THAT READERS and critics have been eagerly anticipating for over a decade, Gilead is an astonishingly imagined story of remarkable lives. John Ames is a preacher, the son of a preacher and the grandson (both maternal and paternal) of preachers. It’s 1956 in Gilead, Iowa, towards the end of the Reverend Ames’s life, and he is absorbed in recording his family’s story, a legacy for the young son he will never see grow up. Haunted by his grandfather’s presence, John tells of the rift between his grandfather and his father: the elder, an angry visionary who fought for the abolitionist cause, and his son, an ardent pacifist. He is troubled, too, by his prodigal namesake, Jack (John Ames) Boughton, his best friend’s lost son who returns to Gilead searching for forgiveness and redemption. Told in John Ames’s joyous, rambling voice that finds beauty, humour and truth in the smallest of life’s details, Gilead is a song of celebration and acceptance of the best and the worst the world has to offer. At its heart is a tale of the sacred bonds between fathers and sons, pitch-perfect in style and story, set to dazzle critics and readers alike."\n"9780002261982 A new \'Christie for Christmas\' -- a full-length novel adapted from her acclaimed play by Charles Osborne Following BLACK COFFEE and THE UNEXPECTED GUEST comes the final Agatha Christie play novelisation, bringing her superb storytelling to a new legion of fans. Clarissa, the wife of a Foreign Office diplomat, is given to daydreaming. \'Supposing I were to come down one morning and find a dead body in the library, what should I do?\' she muses. Clarissa has her chance to find out when she discovers a body in the drawing-room of her house in Kent. Desperate to dispose of the body before her husband comes home with an important foreign politician, Clarissa persuades her three house guests to become accessories and accomplices. It seems that the murdered man was not unknown to certain members of the house party (but which ones?), and the search begins for the murderer and the motive, while at the same time trying to persuade a police inspector that there has been no murder at all... SPIDER\'S WEB was written in 1954 specifically for Margaret Lockwood and opened first at the Theatre Royal Nottingham before moving to the Savoy Theatre in London on 14 December 1954. With THE MOUSETRAP and WI"\n"9780006178736 A memorable, mesmerizing heroine Jennifer -- brilliant, beautiful, an attorney on the way up until the Mafia\'s schemes win her the hatred of an implacable enemy -- and a love more destructive than hate. A dangerous, dramatic world The Dark Arena of organized crime and flashbulb lit courtrooms where ambitious prosecutors begin their climb to political power."\n"9780006280897 Lewis\' work on the nature of love divides love into four categories; Affection, Friendship, Eros and Charity. The first three come naturally to humanity. Charity, however, the Gift-love of God, is divine, and without this supernatural love, the natural loves become distorted and even dangerous."\n"9780006280934 ""In The Problem of Pain, C.S. Lewis, one of the most renowned Christian authors and thinkers, examines a universally applicable question within the human condition: If God is good and all-powerful, why does he allow his creatures to suffer pain? With his signature wealth of compassion and insight, C.S. Lewis offers answers to these crucial questions and shares his hope and wisdom to help heal a world hungering for a true understanding of human nature.""--Amazon."\n"9780006380832 Until Vasco da Gama discovered the sea-route to the East in 1497-9 almost nothing was known in the West of the exotic cultures and wealth of the Indian Ocean and its peoples. It is this civilization and its destruction at the hands of the West that Richard Hall recreates in this book. Hall\'s history of the exploration and exploitation by Chinese and Arab travellers, and by the Portuguese, Dutch and British alike is one of brutality, betrayal and colonial ambition."\n"9780006470229 A new-cover reissue of the fourth book in the bestselling five-volume sf series created by the world-famous author of the Thomas Covenant chronicles -- and acclaimed as the \'best work of his career\'. Events were not moving as the Amnion had intended. Once again humans had been false in their dealings with the aliens. As the planetoid Thanatos Minor exploded into atoms, the Trumpet hurtled into space only one step ahead of hostile pursuers. On board were Morn Hyland and her force-grown son Davies, cyborg Angus Thermopyle and Captain Nick Succorso -- old enemies thrown together in a desperate bid for survival. For both the Amnion and the UMCP, the immediate capture of the fleeing ship and the secrets it contained was imperative. But for Trumpet\'s exhausted crew the only hope lay in an illegal lab in the distant binary solar system of Valdor Industrial. It would be a journey of unpredictable danger -- from which not all would return..."\n9780006472612 Kate Blackwell is an enigma and one of the most powerful women in the world. But at her ninetieth birthday celebrations there are ghosts of absent friends and absent enemies.\n"9780006482079 Tricked once more by his wily half-brother, Lysaer, Lord of Light, arrives at the tiny harbor town of Merior to find that Arithon\'s ship yards have been abandoned and meticulously destroyed, and that the Master of Shadow has disappeared as if into thin air. Meanwhile Arithon and the Mad Prophet Dakar are traveling on foot through the treacherous Kelhorn Mountains towards the Vastmark clans, there to raise further support for his cause. But raising a warhost is a costly business. Is it mere coincidence that Princess Talith—Lysaer\'s beautiful, headstrong wife—is taken captive and held for a vast ransom by a master brigand? The forces of light and shadow circle and feint, drawing ever closer to a huge conflict. And in the background the Fellowship of Seven Sorcerers and the Koriani Enchantresses watch and plan, and wait."\n"9780006483014 An omnibus volume of the author\'s complete story of the Arthurian epic which includes: ""The sword in the stone"" (1939), ""The witch in the wood"" (1939), ""The ill-made knight"" (1940), ""The candle in the wind"" (published for the first time), and ""The book of Merlyn."" 1996."\n"9780006483892 Available in the U.S. for the first time, this is the second volume in the exceptional Legends of the Riftwar series from ""New York Times""-bestselling authors Feist and Rosenberg."\n"9780006483908 Jimmy the Hand, boy thief of Krondor, lived in the shadows of the city. Though gifted beyond his peers, Jimmy is merely a pickpocket with potential--until he aids Prince Arutha in the rescue of Princess Anita from Duke Guy du Bas-Tyra, and runs afoul of ""Black Guy\'s"" secret police. Facing a choice between disappearing on his own or in a weighted barrel at the bottom of Krondor\'s harbor, Jimmy chooses the former. Forced to flee the only home he\'s ever known, Jimmy finds himself among the unsuspecting rural villagers of Land\'s End, where he hopes to prosper with his talents for con and thievery. But Land\'s End is home to many who tread the crooked path--and to a dark, dangerous presence even the local smugglers don\'t recognize. And suddenly Jimmy\'s youthful bravado and courage are leading him into the maw of chaos . . . and, quite possibly, to his doom."\n"9780006486145 Gareth is just a frightened young lad when he is drafted in to be the whipping-boy for the unruly Prince Dagnarus. Yet as they grow to be men, an unshakable bond is formed. And it is their destiny for them to become the two most powerful - and feared - men in the kingdom. But when Dagnarus decides to become a knight himself, he begins a chain of evil events that threaten to destroy the entire kingdom. Only by uniting the Sovereign Stone can peace be restored, and it is up to Dagnarus\' brother Helmos to try to achieve this impossible task, using his father\'s soldiers against his brother\'s army. All the while, Gareth is gaining mastery over the sinister Void magic, and he is devoted to helping his childhood companion.. This gripping story of magical power and corruption takes the unique viewpoint of focusing on the evil characters, as we follow them from boys to men. Filled with action, suspense and wonderfully imaginative characters, Water From the Well of Darkness is set to elevate the careers of bestselling authors Weis & Hickman to spectacular new heights."\n"9780006490456 Newly-Jacketed Edition Designed To Celebrate The 50Th Anniversary Of Christie S Faultlessly Plotted Witness For The Prosecution And Other Outstanding Plays. The Perfect Complement To The Latest Edition Of The Mousetrap And Selected Plays (50Th Aniversary Edition). Headlining This Book Is Witness For The Prosecution Christie S Highly Successful Stage Play Which Won The New York Drama Critics Circle Award For Best Foreign Play. A Stunning Courtroom Drama, It Tells The Story Of A Scheming Wife Testifying Against Her Husband In A Shocking Murder Trial. The Wild Beauty Of A Seaside House Perched High On The Devonshire River Tern Provides A Stunning Back-Drop In Towards Zero As A Psychopathic Murderer Homes In On The Unsuspecting Victims. Passion, Murder And Love Are The Deadly Ingredients In Verdict, Making It One Of Christie S More Unusual Thrillers And Prompting Her To Label It The Best Play I Have Written With The Exception Of Witness For The Prosecution . Go Back For Murder Tells The Story Of The Young And Feisty Carla Who, Orphaned At The Tender Age Of Five, Discovers Her Mother Was Imprisioned For Murdering Her Father And Determines To Prove Her Innocence."')

In [71]:
db_books = Chroma.from_documents(
    documents=documents,
    embedding=HuggingFaceEmbeddings(model_name="all-MiniLM-L6-v2")
)

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

BertModel LOAD REPORT from: sentence-transformers/all-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

In [73]:
query = "A book to teach children about nature"
docs = db_books.similarity_search(query, k = 10)
docs

[Document(id='351cf648-733d-4eb8-b193-1e052394a6f1', metadata={'source': 'tagged_description.txt'}, page_content='"9780067575208 First published more than three decades ago, this reissue of Rachel Carson\'s award-winning classic brings her unique vision to a new generation of readers. Stunning new photographs by Nick Kelsh beautifully complement Carson\'s intimate account of adventures with her young nephew, Roger, as they enjoy walks along the rocky coast of Maine and through dense forests and open fields, observing wildlife, strange plants, moonlight and storm clouds, and listening to the ""living music"" of insects in the underbrush. ""If a child is to keep alive his inborn sense of wonder."" Writes Carson, ""he needs the companionship of at least one adult who can share it, rediscovering with him the joy, excitement and mystery of the world we live in."" The Sense of Wonder is a refreshing antidote to indifference and a guide to capturing the simple power of discovery that Carson views as essential to life. In her insightful new introduction, Linda Lear remembers Rachel Carson\'s groundbreaking achievements in the context of the legendary environmentalist\'s personal commitment to introducing young and old to the miracles of nature. Kelsh\'s lush photographs inspire sensual, tactile reactions: masses of leaves floating in a puddle are just waiting to be scooped up and examined more closely. An image of a narrow path through the trees evokes the earthy scent of the woods after a summer rain. Close-ups of mosses and miniature lichen fantasy-lands will spark innocent\'as well as more jaded\'imaginations. Like a curious child studying things underfoot and within reach, Kelsh\'s camera is drawn to patterns in nature that too often elude hurried adults\'a stand of beech trees in the springtime, patches of melting snow and the ripples from a pebble tossed into a slow-moving stream. The Sense of Wonder is a timeless volume that will be passed on from children to grandchildren, as treasured as the memory of an early-morning walk when the song of a whippoorwill was heard as if for the first time."\n9780070488205 The Blessed Virgin\'s deliverance of a prophecy to a peasant girl in Fatima in 1914 is followed years later by signs and omens including worldwide droughts and famines that signify its imminent fulfillment\n9780071348270 Explains how to improve one\'s existing organization while creating a replacement design for the future and why change is necessary to ensure the future of one\'s business\n"9780071401944 The New York Times Bestseller! Learn how to keep your cool and get the results you want when emotions flare. When stakes are high, opinions vary, and emotions run strong, you have three choices: Avoid a crucial conversation and suffer the consequences; handle the conversation badly and suffer the consequences; or read Crucial Conversations and discover how to communicate best when it matters most. Crucial Conversations gives you the tools you need to step up to life\'s most difficult and important conversations, say what\'s on your mind, and achieve the positive resolutions you want. You\'ll learn how to: Prepare for high-impact situations with a six-minute mastery technique Make it safe to talk about almost anything Be persuasive, not abrasive Keep listening when others blow up or clam up Turn crucial conversations into the action and results you want Whether they take place at work or at home, with your neighbors or your spouse, crucial conversations can have a profound impact on your career, your happiness, and your future. With the skills you learn in this book, you\'ll never have to worry about the outcome of a crucial conversation again."\n"9780071418584 ""You\'ll not only break the ice, you\'ll melt it away with your new skills."" -- Larry King ""The lost art of verbal communication may be revitalized by Leil Lowndes."" -- Harvey McKay, author of “How to Swim with the Sharks Without Being Eaten Alive” What is that magic quality makes some people instantly loved and respected? Everyone wants to be their friend (or, if single, their lover!) In business, they rise swiftly to the top of the corporate ladder. What is their ""Midas touch?"" What it boils down to is a more skillful way of dealing with people. The author has spent her career teaching people how to communicate for success. In her book How to Talk to Anyone (Contemporary Books, October 2003) Lowndes offers 92 easy and effective sure-fire success techniques-- she takes the reader from first meeting all the way up to sophisticated techniques used by the big winners in life. In this information-packed book you’ll find: 9 ways to make a dynamite first impression 14 ways to master small talk, ""big talk,"" and body language 14 ways to walk and talk like a VIP or celebrity 6 ways to sound like an insider in any crowd 7 ways to establish deep subliminal rapport with anyone 9 ways to feed someone\'s ego (and know when NOT to!) 11 ways to make your phone a powerful communications tool 15 ways to work a party like a politician works a room 7 ways to talk with tigers and not get eaten alive In her trademark entertaining and straight-shooting style, Leil gives the techniques catchy names so you\'ll remember them when you really need them, including: ""Rubberneck the Room,"" ""Be a Copyclass,"" ""Come Hither Hands,"" “Bare Their Hot Button,” “The Great Scorecard in the Sky,"" and ""Play the Tombstone Game,” for big success in your social life, romance, and business. How to Talk to Anyone, which is an update of her popular book, Talking the Winner\'s Way (see the 5-star reviews of the latter) is based on solid research about techniques that work! By the way, don\'t confuse How to Talk to Anyone with one of Leil\'s previous books, How to Talk to Anybody About Anything. This one is completely different!"\n"9780071428484 The fun and easy way to quickly enhance your French reading skills Easy French Reader is based on the premise that the best way to learn a language is to start reading it, immediately. Suitable for raw beginners to intermediate-level language learners, this popular title features engaging readings of progressive difficulty that allow you to rapidly build your comprehension. Find out what unfamiliar words and phrases mean with the book\'s helpful glossary Discover the nuances of French language and culture as well as the country\'s history through engaging texts Get a feel for authentic French society with readings from contemporary literature"\n"9780071433716 ""A young woman\'s fatal battle with anorexia, in her own words In the tradition of Go Ask Alice, Prozac Nation, and Girl Interrupted, Slim to None grants readers precious access to the emotional and psychological underpinnings of its author. Step-by-step, readers follow Jenny\'s long journey through a ""wasteland"" of failed treatments and therapies, false hope, and abuse by the mental health system that kept her captive most of her life. Although this disease has been at the forefront of public awareness for years, anorexia continues to claim more victims than any other mental illness. Slim to None reveals the glaring inadequacy of the mental health system to treat and fully understand this disease. The first journal of an anorexic to be published posthumously, the book discloses the innermost thoughts, fears, and hopes of a young girl stricken and fighting to recover. Jenny Hendricks painstakingly recorded her experiences as she suffered from and eventually succumbed to this eating disorder. With candor, she recounts being shipped from one doctor to another and subjected to widely varying treatments--all of which ultimately proved unsuccessful. Her father, Gordon Hendricks, fills in this compelling narrative with his own memories of his daughter\'s struggle.""--Publisher\'s description."\n"9780071451383 Practice makes perfect Italian verb tenses goes beyond other verb books to coach you in when and why verb tenses are used. In addition to an array of fully conjugated verbs, you will find clear and concise explanations that pinpoint why specific tenses work in given situations as well as plenty of engaging examples and numerous skill-building exercises. This is the ideal reference/workbook for beginning to intermediate Italian language learners whose goal is to learn to speak and write Italian with fluency."\n"9780072226966 Written by FBI insiders, this updated best-seller offers a look at the legal, procedural, and technical steps of incident response and computer forensics. Including new chapters on forensic analysis and remediation, and real-world case studies, this revealing book shows how to counteract and conquer today’s hack attacks."\n"9780072920963 The best-selling textbook in the field, The Last Dance offers an interdisciplinary introduction to death, dying, and bereavement. Integrating the experiential and the scholarly, as well as the emotional and intellectual dimensions of death and dying, the seventh edition has been thoroughly revised to provide the most cutting-edge coverage of death studies."'),
 Document(id='2730acb5-d536-44d7-a28d-5dee83f6636f', metadata={'source': 'tagged_description.txt'}, page_content='"9780067575208 First published more than three decades ago, this reissue of Rachel Carson\'s award-winning classic brings her unique vision to a new generation of readers. Stunning new photographs by Nick Kelsh beautifully complement Carson\'s intimate account of adventures with her young nephew, Roger, as they enjoy walks along the rocky coast of Maine and through dense forests and open fields, observing wildlife, strange plants, moonlight and storm clouds, and listening to the ""living music"" of insects in the underbrush. ""If a child is to keep alive his inborn sense of wonder."" Writes Carson, ""he needs the companionship of at least one adult who can share it, rediscovering with him the joy, excitement and mystery of the world we live in."" The Sense of Wonder is a refreshing antidote to indifference and a guide to capturing the simple power of discovery that Carson views as essential to life. In her insightful new introduction, Linda Lear remembers Rachel Carson\'s groundbreaking achievements in the context of the legendary environmentalist\'s personal commitment to introducing young and old to the miracles of nature. Kelsh\'s lush photographs inspire sensual, tactile reactions: masses of leaves floating in a puddle are just waiting to be scooped up and examined more closely. An image of a narrow path through the trees evokes the earthy scent of the woods after a summer rain. Close-ups of mosses and miniature lichen fantasy-lands will spark innocent\'as well as more jaded\'imaginations. Like a curious child studying things underfoot and within reach, Kelsh\'s camera is drawn to patterns in nature that too often elude hurried adults\'a stand of beech trees in the springtime, patches of melting snow and the ripples from a pebble tossed into a slow-moving stream. The Sense of Wonder is a timeless volume that will be passed on from children to grandchildren, as treasured as the memory of an early-morning walk when the song of a whippoorwill was heard as if for the first time."\n9780070488205 The Blessed Virgin\'s deliverance of a prophecy to a peasant girl in Fatima in 1914 is followed years later by signs and omens including worldwide droughts and famines that signify its imminent fulfillment\n9780071348270 Explains how to improve one\'s existing organization while creating a replacement design for the future and why change is necessary to ensure the future of one\'s business\n"9780071401944 The New York Times Bestseller! Learn how to keep your cool and get the results you want when emotions flare. When stakes are high, opinions vary, and emotions run strong, you have three choices: Avoid a crucial conversation and suffer the consequences; handle the conversation badly and suffer the consequences; or read Crucial Conversations and discover how to communicate best when it matters most. Crucial Conversations gives you the tools you need to step up to life\'s most difficult and important conversations, say what\'s on your mind, and achieve the positive resolutions you want. You\'ll learn how to: Prepare for high-impact situations with a six-minute mastery technique Make it safe to talk about almost anything Be persuasive, not abrasive Keep listening when others blow up or clam up Turn crucial conversations into the action and results you want Whether they take place at work or at home, with your neighbors or your spouse, crucial conversations can have a profound impact on your career, your happiness, and your future. With the skills you learn in this book, you\'ll never have to worry about the outcome of a crucial conversation again."\n"9780071418584 ""You\'ll not only break the ice, you\'ll melt it away with your new skills."" -- Larry King ""The lost art of verbal communication may be revitalized by Leil Lowndes."" -- Harvey McKay, author of “How to Swim with the Sharks Without Being Eaten Alive” What is that magic quality makes some people instantly loved and respected? Everyone wants to be their friend (or, if single, their lover!) In business, they rise swiftly to the top of the corporate ladder. What is their ""Midas touch?"" What it boils down to is a more skillful way of dealing with people. The author has spent her career teaching people how to communicate for success. In her book How to Talk to Anyone (Contemporary Books, October 2003) Lowndes offers 92 easy and effective sure-fire success techniques-- she takes the reader from first meeting all the way up to sophisticated techniques used by the big winners in life. In this information-packed book you’ll find: 9 ways to make a dynamite first impression 14 ways to master small talk, ""big talk,"" and body language 14 ways to walk and talk like a VIP or celebrity 6 ways to sound like an insider in any crowd 7 ways to establish deep subliminal rapport with anyone 9 ways to feed someone\'s ego (and know when NOT to!) 11 ways to make your phone a powerful communications tool 15 ways to work a party like a politician works a room 7 ways to talk with tigers and not get eaten alive In her trademark entertaining and straight-shooting style, Leil gives the techniques catchy names so you\'ll remember them when you really need them, including: ""Rubberneck the Room,"" ""Be a Copyclass,"" ""Come Hither Hands,"" “Bare Their Hot Button,” “The Great Scorecard in the Sky,"" and ""Play the Tombstone Game,” for big success in your social life, romance, and business. How to Talk to Anyone, which is an update of her popular book, Talking the Winner\'s Way (see the 5-star reviews of the latter) is based on solid research about techniques that work! By the way, don\'t confuse How to Talk to Anyone with one of Leil\'s previous books, How to Talk to Anybody About Anything. This one is completely different!"\n"9780071428484 The fun and easy way to quickly enhance your French reading skills Easy French Reader is based on the premise that the best way to learn a language is to start reading it, immediately. Suitable for raw beginners to intermediate-level language learners, this popular title features engaging readings of progressive difficulty that allow you to rapidly build your comprehension. Find out what unfamiliar words and phrases mean with the book\'s helpful glossary Discover the nuances of French language and culture as well as the country\'s history through engaging texts Get a feel for authentic French society with readings from contemporary literature"\n"9780071433716 ""A young woman\'s fatal battle with anorexia, in her own words In the tradition of Go Ask Alice, Prozac Nation, and Girl Interrupted, Slim to None grants readers precious access to the emotional and psychological underpinnings of its author. Step-by-step, readers follow Jenny\'s long journey through a ""wasteland"" of failed treatments and therapies, false hope, and abuse by the mental health system that kept her captive most of her life. Although this disease has been at the forefront of public awareness for years, anorexia continues to claim more victims than any other mental illness. Slim to None reveals the glaring inadequacy of the mental health system to treat and fully understand this disease. The first journal of an anorexic to be published posthumously, the book discloses the innermost thoughts, fears, and hopes of a young girl stricken and fighting to recover. Jenny Hendricks painstakingly recorded her experiences as she suffered from and eventually succumbed to this eating disorder. With candor, she recounts being shipped from one doctor to another and subjected to widely varying treatments--all of which ultimately proved unsuccessful. Her father, Gordon Hendricks, fills in this compelling narrative with his own memories of his daughter\'s struggle.""--Publisher\'s description."\n"9780071451383 Practice makes perfect Italian verb tenses goes beyond other verb books to coach you in when and why verb tenses are used. In addition to an array of fully conjugated verbs, you will find clear and concise explanations that pinpoint why specific tenses work in given situations as well as plenty of engaging examples and numerous skill-building exercises. This is the ideal reference/workbook for beginning to intermediate Italian language learners whose goal is to learn to speak and write Italian with fluency."\n"9780072226966 Written by FBI insiders, this updated best-seller offers a look at the legal, procedural, and technical steps of incident response and computer forensics. Including new chapters on forensic analysis and remediation, and real-world case studies, this revealing book shows how to counteract and conquer today’s hack attacks."\n"9780072920963 The best-selling textbook in the field, The Last Dance offers an interdisciplinary introduction to death, dying, and bereavement. Integrating the experiential and the scholarly, as well as the emotional and intellectual dimensions of death and dying, the seventh edition has been thoroughly revised to provide the most cutting-edge coverage of death studies."'),

In [75]:
# We add .replace('"', '') to remove any potential quotes from the CSV export
isbn_id = docs[0].page_content.split()[0].replace('"', '').strip()
books[books["isbn13"] == int(isbn_id)]

,isbn13,isbn10,title,authors,categories,thumbnail,description,published_year,average_rating,num_pages,ratings_count,title_and_subtitle,tagged_description
442,9780067575208,006757520X,The Sense of Wonder,Rachel Carson,Nature,http://books.google.com/books/content?id=Zee5S...,"First published more than three decades ago, t...",1998.0,4.39,112.0,1160.0,The Sense of Wonder,9780067575208 First published more than three ...

In [77]:
def retrieve_semantic_recommendations(
        query: str,
        top_k: int = 10,
) -> pd.DataFrame:
    recs = db_books.similarity_search(query, k = 10)

    books_list = []

    for i in range(0, len(recs)):
        books_list += [int(recs[i].page_content.strip('"').split()[0])]
    return books[books["isbn13"].isin(books_list)]

In [78]:
retrieve_semantic_recommendations("A book to teach children about nature")

,isbn13,isbn10,title,authors,categories,thumbnail,description,published_year,average_rating,num_pages,ratings_count,title_and_subtitle,tagged_description
391,9780061205699,0061205699,To Kill a Mockingbird (slipcased edition),Harper Lee,Fiction,http://books.google.com/books/content?id=M9lKH...,"At the age of eight, Scout Finch is an entrenc...",2006.0,4.27,323.0,250.0,To Kill a Mockingbird (slipcased edition),"9780061205699 At the age of eight, Scout Finch..."
442,9780067575208,006757520X,The Sense of Wonder,Rachel Carson,Nature,http://books.google.com/books/content?id=Zee5S...,"First published more than three decades ago, t...",1998.0,4.39,112.0,1160.0,The Sense of Wonder,9780067575208 First published more than three ...
1878,9780385732338,0385732333,Cuba 15,Nancy Osa,Juvenile Fiction,http://books.google.com/books/content?id=D1ObA...,"Violet Paz, a Chicago high school student, rel...",2005.0,3.45,304.0,1028.0,Cuba 15,"9780385732338 Violet Paz, a Chicago high schoo..."
2215,9780440420637,0440420636,The Green Toenails Gang,Marjorie Weinman Sharmat,Juvenile Fiction,http://books.google.com/books/content?id=yP1lc...,"Wealthy Olivia Sharp, agent for secrets, uncov...",2005.0,3.74,72.0,41.0,The Green Toenails Gang,"9780440420637 Wealthy Olivia Sharp, agent for ..."
2457,9780465016907,0465016901,The Drama of the Gifted Child,NaN,Psychology,http://books.google.com/books/content?id=TgtTz...,Why are many of the most successful people pla...,1997.0,4.09,144.0,11373.0,The Drama of the Gifted Child: The Search for ...,9780465016907 Why are many of the most success...